namespace TemplateMonkey
{
    public static class ModHelperData
    {
        public const string WorksOnVersion = "1.0";
        public const string Version = "1.0.0";
        public const string Name = "Template Monkey";
        public const string Description =
            "Tower generated by Jonyboylovespie's tower maker.";

        public const string RepoOwner = "Jonyboylovespie";
        public const string RepoName = "";
        public const string Icon = "";
    }
}